apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  labels:
    app: redisinsight
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.REDISINSIGHT_PORT }}
      nodePort: {{ .Values.REDISINSIGHT_NODE_PORT }}
      name: http
  selector:
    app: redisinsight