apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsadf-api-volume-claim
  labels:
    app: lsadf-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi