apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret  # Name of the secret
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.KEYCLOAK_ADMIN }}"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.KEYCLOAK_ADMIN_PASSWORD }}"
  KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HEALTH_ENABLED: "true"
  KC_LOG_LEVEL: "info"
  KC_HOSTNAME_PORT: "8081"
  KC_DB: "postgres"
  KC_DB_URL: "{{ .Values.DB_URL_DOCKER }}"
  KC_DB_USERNAME: "{{ .Values.DB_USERNAME }}"
  KC_DB_PASSWORD: "{{ .Values.DB_PASSWORD }}"
  KC_HOSTNAME: "keycloak.local"

