temporal:
  namespace: lsadf
  game-session-task-queue: game_session_queue

cache:
  redis:
    enabled: ${CACHE_ENABLED}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}
    embedded: false
  expiration:
    game-save-ownership-expiration-seconds: ${GAME_SAVE_OWNERSHIP_EXPIRATION_SECONDS}
    local-user-expiration-seconds: ${LOCAL_USER_EXPIRATION_SECONDS}
    characteristics-expiration-seconds: ${CHARACTERISTICS_EXPIRATION_SECONDS}
    currency-expiration-seconds: ${CURRENCY_EXPIRATION_SECONDS}
    inventory-expiration-seconds: ${INVENTORY_EXPIRATION_SECONDS}
    stage-expiration-seconds: ${STAGE_EXPIRATION_SECONDS}

logging:
  file:
    path: classpath:logback.xml

shutdown:
  flush-cache-at-shutdown: true

clock:
  time-zone: "Europe/Paris"

configuration-display:
  enabled: true

jpa:
  enabled: true