services:
  postgres:
    image: postgres:16.0-alpine
    profiles:
      - db
      - backend
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    profiles:
      - db
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./docker-data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "7502:80"
    networks:
      - backend

  lsadf_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lsadf_backend
    profiles:
      - backend
    ports:
      - "8080:8080"
    environment:
      - SLEEP_ENABLED=true
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge