services:
  postgres:
    image: postgres:16.0-alpine
    profiles:
      - db
      - backend
    container_name: postgres
    environment:
      POSTGRES_DB: lsadf
      POSTGRES_USER: lsadf
      POSTGRES_PASSWORD: lsadf
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    profiles:
      - db
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./docker-data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "7502:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge