apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.KEYCLOAK_PORT }}
  type: ClusterIP