# Configuration for standalone mode
# This profile enables both API controllers and worker functionality

api:
  enabled: true
  swagger-enabled: true

# Optimal connection pool settings for standalone mode (handling both API and workers)
spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 8

# Enable full management endpoints for monitoring standalone application
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus