apiVersion: v1
kind: Service
metadata:
  name: lsadf-api-service
spec:
  selector:
    app: lsadf-api
  ports:
    - protocol: TCP
      port: {{ .Values.LSADF_API_PORT }}
      name: http
  type: ClusterIP