apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.POSTGRESQL_PORT }}
      name: http
      protocol: TCP
  selector:
    app: postgres