apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret  # Name of the secret
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.DB_NAME }}"
  POSTGRES_USER: "{{ .Values.DB_USERNAME }}"
  POSTGRES_PASSWORD: "{{ .Values.DB_PASSWORD }}"