apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsadf-api
  namespace: lsadf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsadf-api
  template:
    metadata:
      labels:
        app: lsadf-api
    spec:
      hostAliases:
        - ip: {{ .Values.K8S_IP }}
          hostnames:
            - {{ .Values.LSADF_API_HOST }}
      containers:
        - name: lsadf-api
          image: {{ .Values.LSADF_API_DOCKER_IMAGE }}
          imagePullPolicy: {{ .Values.DOCKER_IMAGE_PULL_POLICY }}
          env:
            - name: SLEEP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: lsadf-api-secret
          ports:
            - containerPort: {{ .Values.LSADF_API_PORT }}
              name: http
          volumeMounts:
            - mountPath: /app/logs
              name: lsadf-api-volume
          resources:
            limits:
              memory: "{{ .Values.LSADF_API_RESOURCE_LIMIT_MEMORY }}"
              cpu: "{{ .Values.LSADF_API_RESOURCE_LIMIT_CPU }}"

      volumes:
        - name: lsadf-api-volume
          persistentVolumeClaim:
            claimName: lsadf-api-volume-claim