nginx_ingress:
  enabled: true
  # Configure additional settings for your ingress controller
  controller:
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "false"
      # Adjust these values based on your traffic needs
      proxy-body-size: "10m"
      client-max-body-size: "10m"
      # Enable gzip for better performance
      enable-brotli: "true"
      use-gzip: "true"
      gzip-level: "6"
      gzip-types: "application/json application/xml text/css text/javascript text/plain text/xml application/javascript application/x-javascript"
  # SSL configuration
  ssl:
    enabled: false  # Set to true when you have certificates
    # You can add your certificate configuration here when ready
