FROM eclipse-temurin:25-jdk-noble

ARG module_folder

WORKDIR /app

COPY $module_folder/target/*.jar app.jar
COPY ./docker/startup-dev.sh startup.sh
COPY $module_folder/src/main/resources/logback-docker.xml logback-docker.xml

ENTRYPOINT ["./startup.sh"]