/*
 * Copyright © 2024-2026 LSDAF
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.lsadf.core.infra.web.dto.request.user.creation;

import com.lsadf.core.domain.user.User;
import com.lsadf.core.infra.web.dto.request.RequestModelMapper;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * A MapStruct mapper interface dedicated to transforming {@link UserCreationRequest} objects into
 * {@link User} domain objects.
 *
 * <p>This mapper is used for converting request-layer data received during user creation operations
 * into the application's internal representation for further processing or persistence.
 *
 * <p>The implementation of this interface is automatically generated by MapStruct at compile time.
 */
@Mapper
public interface UserCreationRequestMapper extends RequestModelMapper<UserCreationRequest, User> {
  UserCreationRequestMapper INSTANCE =
      org.mapstruct.factory.Mappers.getMapper(UserCreationRequestMapper.class);

  @Override
  @Mapping(target = "createdTimestamp", ignore = true)
  @Mapping(target = "id", ignore = true)
  User map(UserCreationRequest userCreationRequestImpl);
}
