apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:2.66-arm64
          ports:
            - containerPort: 8001
              name: http
          envFrom:
            - configMapRef:
                name: redisinsight-config