apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  labels:
    app: redisinsight
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      nodePort: 31093
      name: http
  selector:
    app: redisinsight