apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.REDIS_PORT }}
      name: http
      protocol: TCP
  selector:
    app: redis