apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      name: http
      nodePort: {{ .Values.PGADMIN_NODE_PORT }}
  type: NodePort