apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret  # Name of the secret
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "{{ .Values.PGADMIN_DEFAULT_EMAIL }}"
  PGADMIN_DEFAULT_PASSWORD: "{{ .Values.PGADMIN_DEFAULT_PASSWORD }}"